version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99

- package-ecosystem: docker
  directory: "/dockerfiles/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
