run:
  timeout: 5m
  deadline: 10m

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/linkedin/Burrow
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - ifElseChain
  funlen:
    lines: 350
    statements: 200

linters:
  disable-all: true
  enable:
    - bodyclose
    # - deadcode
    - depguard
    - dogsled
    # - dupl
    # - errcheck
    - funlen
    - gocritic
    - gocyclo
    # - gofmt
    - goimports
    - revive
    # - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    # - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    # - varcheck
    - whitespace
    - goconst
    - unused
    # - gochecknoinits

issues:
  exclude:
    - consider giving a name to these results
    - include an explanation for nolint directive
