project_name: Burrow

builds:
- main: main.go
  binary: burrow
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
archives:
- format: tar.gz
  files:
  - LICENSE
  - NOTICE
  - README.md
  - CHANGELOG.md
  - config/burrow.toml
  - config/default-email.tmpl
  - config/default-http-delete.tmpl
  - config/default-http-post.tmpl
  - config/default-slack-delete.tmpl
  - config/default-slack-post.tmpl
snapshot:
  name_template: "{{ .FullCommit }}"
dockers:
- goos: linux
  goarch: amd64
  goarm: ''
  binaries:
  - burrow
  dockerfile: Dockerfile.gorelease
  image_templates:
  - 'docker.pkg.github.com/linkedin/burrow/burrow:latest'
  - 'docker.pkg.github.com/linkedin/burrow/burrow:{{ .Tag }}'
  extra_files:
  - docker-config/burrow.toml
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{ .Version }}"
  - "--label=org.label-schema.name={{ .ProjectName }}"
  - "--label=org.label-schema.vcs=https://github.com/linkedin/Burrow"
  - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
