FROM alpine:3.19
LABEL maintainer="LinkedIn Burrow https://github.com/linkedin/Burrow"

RUN adduser -u 10001 burrow -D
USER burrow

WORKDIR /app
COPY burrow /app/

CMD ["/app/burrow", "--config-dir", "/etc/burrow"]
