# https://github.com/linkedin/Burrow/wiki/Configuration

[general]
pidfile="burrow.pid"
# stdout-logfile="burrow.out"
access-control-allow-origin="burrow.frankfurt1.gygkube.com"

[logging]
# filename="logs/burrow.log"
level="info"
# maxsize=100
# maxbackups=30
# maxage=10
use-localtime=false
# use-compression=true

[zookeeper]
servers=[ "zookeeper1.kafka1.gygkube.com:2181" ]
timeout=6
root-path="/burrow"

[client-profile.kafka1]
client-id="burrow-test"
kafka-version="1.1.0"
sasl="kafka1"

[cluster.kafka1]
class-name="kafka"
servers=[ "kafka1.kafka1.frankfurt1.com:9092" ]
client-profile="kafka1"
topic-refresh=120
offset-refresh=30

[consumer.kafka1]
class-name="kafka"
cluster="kafka1"
servers=[ "kafka1.kafka1.frankfurt1.com:9092" ]
client-profile="kafka1"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-|devops).*$"
group-whitelist=""

[consumer.kafka1_zk]
class-name="kafka_zk"
cluster="kafka1"
servers=[ "zookeeper1.kafka1.gygkube.com:2181" ]
zookeeper-path="/burrow"
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-|devops).*$"
group-whitelist=""

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1

# [notifier.default]
# class-name="http"
# url-open="http://someservice.example.com:1467/v1/event"
# interval=60
# timeout=5
# keepalive=30
# extras={ api_key="REDACTED", app="burrow", tier="STG", fabric="mydc" }
# template-open="conf/default-http-post.tmpl"
# template-close="conf/default-http-delete.tmpl"
# method-close="DELETE"
# send-close=true
# threshold=1
